# configuración para render.com
# archivo: render.yaml

services:
  - type: web
    name: dabot-v2
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DAILY_CHANNEL_ID  
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dabot-db
          property: connectionString
    autoDeploy: false
    
databases:
  - name: dabot-db
    databaseName: dabot
    user: dabot
    plan: free
