# configuración para render.com
# archivo: render.yaml

# Configuración optimizada para Render.com (sin Docker)
# Archivo: render.yaml

services:
  - type: web
    name: dabot-v2
    env: python
    plan: starter
    runtime: python-3.12.5
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements-render.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PREFIX
        value: "!"
      - key: WEB_PORT
        value: "10000" 
      - key: WEB_HOST
        value: "0.0.0.0"
      - key: WEB_ENABLED
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12.5"
      - key: LOG_LEVEL
        value: "INFO"
      - key: TIMEZONE
        value: "UTC"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: dabot-v2-db
          property: connectionString
    autoDeploy: true
    region: oregon
    
# Eliminar sección de databases duplicada y usar solo una
databases:
  - name: dabot-v2-db
    databaseName: dabot_v2
    user: dabot_user
    plan: starter
